#define ERRSTRING_LEN 250

extern int ecrt_err_to_stderr;
extern char ecrt_errstring[ERRSTRING_LEN];

#define ERRPRINTF(...) do { \
    if (ecrt_err_to_stderr) { \
        fprintf(stderr, __VA_ARGS__);\
    }\
    else {\
        snprintf(ecrt_errstring, ERRSTRING_LEN, __VA_ARGS__);\
        ecrt_errstring[ERRSTRING_LEN-1] = '\0';\
    }\
  }  while (0)

extern int ecrt_errcode;

#define ECRT_ERRCLEAR 0
/* errors in common.c */
#define ECRT_ERROPENMASTER1 100
#define ECRT_ERROPENMASTER2 101
#define ECRT_ERROPENMASTER3 102
#define ECRT_ERROPENMASTER4 103
/* errors in domain.c */
#define ECRT_ERRDOMAINSIZE  200
#define ECRT_ERRDOMAINDATA  201
#define ECRT_ERRDOMAINPROCESS 202
#define ECRT_ERRDOMAINQUEUE 203
#define ECRT_ERRDOMAINSTATE 204
/* errors in master.c */
#define ECRT_ERRRESERVE 300
#define ECRT_ERRMASTERCREATE 301
#define ECRT_ERRMASTERCREATE1 302
#define ECRT_ERRMASTERSLAVECONFIG 303
#define ECRT_ERRMASTERSLAVECONFIG1 304
#define ECRT_ERRMASTERSELECTREFERENCECLOCK 305
#define ECRT_ERRMASTER 306
#define ECRT_ERRMASTERGETSLAVE 307
#define ECRT_ERRMASTERGETSYNCMANAGER 308
#define ECRT_ERRMASTERGETPDO 309
#define ECRT_ERRMASTERGETPDOENTRY 310
#define ECRT_ERRMASTERSDODOWNLOAD 311
#define ECRT_ERRMASTERSDODOWNLOADCOMPLETE 312
#define ECRT_ERRMASTERSDOUPLOAD 313
#define ECRT_ERRMASTERWRITEIDN 314
#define ECRT_ERRMASTERREADIDN 315
#define ECRT_ERRMASTERACTIVATE 316
#define ECRT_ERRMASTERACTIVATE1 317
#define ECRT_ERRMASTERDEACTIVATE 318
#define ECRT_ERRMASTERSETSENDINTERVAL 319
#define ECRT_ERRMASTERSEND 320
#define ECRT_ERRMASTERRECEIVE 321
#define ECRT_ERRMASTERSTATE 322
#define ECRT_ERRMASTERLINKSTATE 323
#define ECRT_ERRMASTERAPPLICATIONTIME 324
#define ECRT_ERRMASTERSYNCREFERENCECLOCK 325
#define ECRT_ERRMASTERSYNCSLAVECLOCKS 326
#define ECRT_ERRMASTERREFERENCECLOCKTIME 327
#define ECRT_ERRMASTERSYNCMONITORQUEUE 328
#define ECRT_ERRMASTERSYNCMONITORPROCESS 329
#define ECRT_ERRMASTERRESET 330

/* errors in req_request.c */
#define ECRT_ERRREQREQUESTSTATE 400
#define ECRT_ERRREQREQUESTSTATE1 401
#define ECRT_ERRREQREQUESTSIZE 402
#define ECRT_ERRREQREQUESTREAD 403

/* errors in sdo_request.c */
#define ECRT_ERRSLAVECFGSYNCMANAGER 500
#define ECRT_ERRSLAVECFGWATCHDOG 501
#define ECRT_ERRSLAVECFGPDOASSIGNADD 502
#define ECRT_ERRSLAVECFGPDOASSIGNCLEAR 503
#define ECRT_ERRSLAVECFGPDOMAPPINGADD 504
#define ECRT_ERRSLAVECFGPDOMAPPINGCLEAR 505
#define ECRT_ERRSLAVECFGPDOS 506
#define ECRT_ERRSLAVECFGREGPDOENTRY 507
#define ECRT_ERRSLAVECFGREGPDOENTRY1 508
#define ECRT_ERRSLAVECFGREGPDOENTRYPOS 509
#define ECRT_ERRSLAVECFGREGPDOENTRYPOS1 510
#define ECRT_ERRSLAVECFGDC 511
#define ECRT_ERRSLAVECFGSDO 512
#define ECRT_ERRSLAVECFGCOMPLETESDO 513
#define ECRT_ERRSLAVECFGEMERGSIZE 514
#define ECRT_ERRSLAVECFGEMERGPOP 515
#define ECRT_ERRSLAVECFGEMERGCLEAR 516
#define ECRT_ERRSLAVECFGEMERGOVERRUNS 517
#define ECRT_ERRSLAVECFGCREATESDOREQUEST 518
#define ECRT_ERRSLAVECFGCREATESDOREQUEST1 519
#define ECRT_ERRSLAVECFGCREATESDOREQUEST2 520
#define ECRT_ERRSLAVECFGCREATEREGREQUEST 521
#define ECRT_ERRSLAVECFGCREATEREGREQUEST1 522
#define ECRT_ERRSLAVECFGCREATEREGREQUEST2 523
#define ECRT_ERRSLAVECFGCREATEVOEHANDLER 524
#define ECRT_ERRSLAVECFGCREATEVOEHANDLER1 525
#define ECRT_ERRSLAVECFGCREATEVOEHANDLER2 526
#define ECRT_ERRSLAVECFGSTATE 527
#define ECRT_ERRSLAVECFGIDN 528
/* errors in sdo_request */
#define ECRT_ERRSDOREQUESTINDEX 600
#define ECRT_ERRSDOREQUESTTIMEOUT 601
#define ECRT_ERRSDOREQUESTSTATE 602
#define ECRT_ERRSDOREQUESTSTATE1 603
#define ECRT_ERRSDOREQUESTSTATE2 604
#define ECRT_ERRSDOREQUESTREAD 605
#define ECRT_ERRSDOREQUESTWRITE 606
/* errors in voe_handler.c */
#define ECRT_ERRVOEHNDSENDHEADER 700
#define ECRT_ERRVOEHNDRECEIVEDHEADER 701
#define ECRT_ERRVOEHNDREAD 702
#define ECRT_ERRVOEHNDREADNOSYNC 703
#define ECRT_ERRVOEHNDWRITE 704
#define ECRT_ERRVOEHNDEXECUTE 705
#define ECRT_ERRVOEHNDEXECUTE1 706
#define ECRT_ERRVOEHNDEXECUTE2 707
